export const GET_TOP_TRACKS = "GET_TOP_TRACKS";
export const SET_TOP_TRACKS = "SET_TOP_TRACKS";
export const GET_TRACKS_BY_ARTIST_ID = "GET_TRACKS_BY_ARTIST_ID";
export const SET_TRACKS_BY_ARTIST_ID = "SET_TRACKS_BY_ARTIST_ID";

export const GET_ALBUMS_BY_ARTIST_ID = "GET_ALBUMS_BY_ARTIST_ID";
export const SET_ALBUMS_BY_ARTIST_ID = "SET_ALBUMS_BY_ARTIST_ID";

export const GET_SIMILAR_BY_ARTIST_ID = "GET_SIMILAR_BY_ARTIST_ID";
export const SET_SIMILAR_BY_ARTIST_ID = "SET_SIMILAR_BY_ARTIST_ID";

export const GET_ARTIST = "GET_ARTIST";
export const SET_ARTIST = "SET_ARTIST";

export const GET_ARTISTS_BY_TAG = "GET_ARTISTS_BY_TAG";
export const SET_ARTISTS_BY_TAG = "SET_ARTISTS_BY_TAG";
export const GET_TRACKS_BY_TAG = "GET_TRACKS_BY_TAG";
export const SET_TRACKS_BY_TAG = "SET_TRACKS_BY_TAG";

export const GET_ALBUM_BY_ID = "GET_ALBUM_BY_ID";
export const SET_ALBUM_BY_ID = "SET_ALBUM_BY_ID";

export const SEARCH_TRACKS = "SEARCH_TRACKS";
export const SET_SEARCH_TRACKS = "SET_SEARCH_TRACKS";

export const SEARCH_ARTISTS = "SEARCH_ARTISTS";
export const SET_SEARCH_ARTISTS = "SET_SEARCH_ARTISTS";

export const SEARCH_ALBUMS = "SEARCH_ALBUMS";
export const SET_SEARCH_ALBUMS = "SET_SEARCH_ALBUMS";